sudo: required
dist: trusty
notifications:
  email: false
services:
- docker
language: java
jdk:
- oraclejdk8
- openjdk10
env:
  matrix:
  - DOCKER_VERSION=17.03.1~ce
  - DOCKER_VERSION=17.06.2~ce DOCKER_CE=1
  - DOCKER_VERSION=17.09.1~ce DOCKER_CE=1
  - DOCKER_VERSION=17.12.1~ce DOCKER_CE=1 UPLOAD_SONATYPE=1
  global:
  - secure: RsCnWltoLaQ6O/fYAQPSRW2flnzQDZAum3h9diq2Rde3AhLmL/2d1MhMzZwpb1GVU3jmaB6RvkxIG1m4vr4qm1cvHBu2sPGaIJjhMyaVbXTwwEGNW1wVyl8SujgxQpZJS3T/D36YebW9NZIdgDHy52jpc3BNChQhFxDYQfMrhN66YRJhAfWdMepTKf2LFxi2kRelwMeIabohWaz170ylqyZ9px+hmSmm0ppEky9suQZSzVma79IQpEEiCIaoSNZLFHPTSsOPWO5lkGFCPCB38oRBMxR3Bj41ZWgqcKfiEveBq8Ys03xQwv4f6KvXVDn9WdtGTvelf/cLjvC89Ww2A69DBiZg6YZFTSSSebKUEt5gOkbEgobX0LYYRUulRW7PSz70S5vuyTvGuHMQsMvKY7PiYZaBjPukTo+NcUXSw7fz/UEpcNADY629CmzLiojNIR5vY+2z4il7Ti/b5jddWVqaVF9FmrHEnogdpgUsk/TywGbsAvWXQD9E5x4zPbSNtuthCaII1hUN+23Z7zAW+MvGBt02lg9zPNJw8asj+LPhH6Y/Xa+9HikF8rCdMDsmuj6UMYkOW3z+ZWR4EE+vN+dVSYwpo1HyxfxG51554b1SUszNwkSWVCQAavV0b+NAWzawuh4fuHQ+T3LlV37Bt1MkDYmR/D7RB8HlgUpBi1k=
  - secure: oknSXvbDjdoD/srMS4nDoSvwwzg+rEUjDy+NKotBFRccFEgXX2r+qy9NjkNz0yE84MTMkXmwoeZLaaSCtP8ZsXNONvOQZ/DYRG+P6buK3ZdNz+mTlFUdERct1FBeVKKBvjA/wLF+EdiqOy82SK5Z32i+d9Rsfg2FRXbWFy5TXmrbgH29B/e/s4ISyeAWR1jmn7Q1jBa1jJxPCbBp2DEzuLA5+gBSO0EQGcOPV2UDJwCKk4Q9XvVG4vz7Zn+Igr0MlS194T1iv9IPNW1Da686aYpltfSNtGMvOeHnHj4iQoeUBvI9+Kw70SnG1RRkEgcPKkiVD2A1cVH6W5d8j86ahck+NQvMMrC9sbQR8kDG+yTn2DDdxUbkl6HZv7B9cpCmjvzlox86d3m55+QiA7DCWHbUGDCrXco5nyhcrujUcKobqFSLMcox/Eo8n58wVBRO3CaK90KMnYh+EAc2WfghABgt5meRVVPuqXtNbOG8ZACuYVLIS5ATa/7IH1VtO1J1AaA3d9FcXx04JGzAhhjQfYFtYp9twAysMgW3iomk8iqrZd1ASZtCLJzZZldWqWg+DHjWj8vv37l8QOTnVP5eyVKeGvvLbakxbbLWZ3MaQU6Lb5J4vOKha/pBn+XmcUHBvWglrebaAcDpui+5PAe6qlKZwBE/PQK2zdrVKXlxjsA=
  - secure: Xx9OdwcIBJAnk0VxN/bIh56C6jp1wYLSsqHemmridXPpkRfCGh2mYQvB1bxPZNeD5Fk2AiyurkLz3U3B69fHXH7qQbZLWqTOP90mul38uYQybeqHL7r/8erTrxMpAFP1etGxIhILpR3lryaZJQzk/mnO4EX4n93Z7UpXh8ihJc//x9aV13dDKbOl3aBtMDxDXHzV6RelAiPWvcRefSj5UF/1CdUzHb1XOwwL1v65MMGeHex3/n8hHoJ1MK3ACxtfN3FIaEkz0HB5iOGA3XsD8wt10czTV/MTyrG5q1vaEXpNmEiSNsJn7iizYdrEjRLQiuFr80Tq4Y3uJuL8pHYch1HOsGXgD2jPNtIcuDqhi+woLBmbHZfC53rrSKKq9FiBsoxGtZ6IpQw155hVnl9UvSXokkxztFiwgpgKMJssEeVoxVTOpOG0172DLdQ+U7WdxMKo4sKZh0/H5Mp4CcMvZxDTsbp9qMOTRCfhVAfRHe6wUKssVd1fbmTYAIWdgDqUvCoQvHhERF8eph5s/uqYNbOoRr6+MPnHgGon0tb/IWb5Jz80s0CFUIaYVq59WWoJAvYzr0A8qZcZlQnnLfaPzFG91X+BuB3P/btHYvmtMDrWQBcVq6MNCWNR+lMAILiOZXJi7Q/AmS3Zy9LRNYRGl+xe+Argh9hEryamNsjM3Jo=
  - secure: mBzPtHHKny8KYH1lTAlkzldPm/279pJ2ZUA1GJYc8jodBy0i7iUWUci0RehMlBPR0dgPvtGJ7AYTPKOz34Lmww+pQh2idrPNcHGrQZUVjDfbRNBwoD7sAUvGGlNj5TCFofYd9Njua3LI93pePTLDpxloxso9CsdwmBQSm9X1/1EABiE0FwxzLtR36fxFTz7ny/dW6r49WLK2VvYwGXyb35hnPH1UoISLrPJ/GZLxgA3lcY+8bMIRpEYNtkydGHTRUU929GhB+cbX+wH5NGteCL+Y5R74MwkdpM/QR4zfULJZKHqoy2wml8AN9tct0mHRhPkteGWJl9Pm8ZOfNfmjOHcA3fIu3FHbLNBDONymG0JhJv9+t5je/Jg1dpFSr4ij6i7gVSYUquXpxnzoclSiWmMc7uUj1S+1LDMHdWEoA735KtQlA3QNjI3YszFPWRjwhwN3ZbzdyqkK35PR19qJKUiDXeW+wfGQpu0koAp4aKtFuP5w3u+Q25YEIA1nCQzbyWxQ8yq9WZ0c4I2qUKYRV9/w0/R/yE3IhIiJw5HtTrOI3fBlOcYfSuv6TVGcXrNN1MG1JBSUHrrsFcVMneFC1JF8YoQKrMAZbKkFrq+iXxE/3zRfznt6M9y0LdGqxolrdWeJYOlvoYpCpEqLbom56mHjFRGqHd47ro6PNRF2BgE=
before_install:
- openssl aes-256-cbc -K $encrypted_7a129298b602_key -iv $encrypted_7a129298b602_iv
  -in secret.asc.enc -out secret.asc -d
- gpg --import secret.asc
- echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
- gpg-connect-agent reloadagent /bye
# check what version of docker is installed beforehand
- dpkg -l | grep docker
# install the version of docker in the DOCKER_VERSION env var
- ./.travis.sh install_docker
# uncomment to double-check that the version/config is correct
# - ./.travis.sh dump_docker_config
- docker version
- docker info

script:
- if [ $TRAVIS_PULL_REQUEST == "false" -a $UPLOAD_SONATYPE == "1" ]; then mvn --settings
  sonatype-settings.xml -Pdeploy-artifacts clean deploy -Dsurefire.rerunFailingTestsCount=1;
  fi
- if [ $TRAVIS_PULL_REQUEST != "false" -o $UPLOAD_SONATYPE != "1" ]; then mvn clean
  test -Dsurefire.rerunFailingTestsCount=1; fi
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
